site_name: vettom.github.io
site_url: https://vettom.github.io
repo_url: https://github.com/vettom
repo_name: Vettom
copyright: Denny Vettom
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - navigation.footer
  language: en
  logo: img/dv-tec-logo-round2cm.png
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode  
      primary: indigo
      accent: lime

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: indigo
      accent: teal

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
      authors_profiles: true
  - tags
  - search
  # - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dennyvettom/
    - icon: fontawesome/brands/github
      link: https://github.com/vettom
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@vettomd
  generator: false

      
